name: MindSpore CI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    branches: [main]

jobs:
  MindSpore-Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install -y python3-pip wget
          pip3 install -r requirements.txt --upgrade
          mkdir -p ~/miniconda3
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
          bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
          rm -rf ~/miniconda3/miniconda.sh
          ~/miniconda3/bin/conda update -n base -c defaults conda -y
          ~/miniconda3/bin/conda init bash
          ~/miniconda3/bin/conda create -n plato_cpu -c conda-forge python=3.9.0
          ~/miniconda3/bin/conda install pytorch torchvision cpuonly -c pytorch -n plato_cpu -y
          ~/miniconda3/bin/conda install mindspore-cpu=1.5.0 -c mindspore -c conda-forge -n plato_cpu -y
          ~/miniconda3/envs/plato_cpu/bin/pip install -r requirements.txt --upgrade

      - name: Training workloads
        run: |
          ~/miniconda3/bin/conda init bash
          ~/miniconda3/bin/conda activate plato_cpu
          ./run --config=configs/MNIST/fedavg_lenet5_mindspore.yml
          ./run --config=configs/MNIST/mistnet_lenet5_mindspore.yml
