name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependences
      run: |
        sudo apt install -y python3-pip git
        git clone https://github.com/TL-System/plato
        cd plato
        pip3 install torch==1.10.0+cpu torchvision==0.11.1+cpu torchaudio==0.10.0+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html
        pip3 install -r requirements.txt --upgrade
        pip3 install -r packages/yolov5/requirements.txt --upgrade
        ./run --config=configs/MNIST/fedavg_lenet5.yml
        ./run --config=configs/MNIST/mistnet_lenet5.yml
        ./run --config=configs/YOLO/fedavg_yolov5.yml
        ./run --config=configs/YOLO/mistnet_yolov5.yml
        
