name: TensorFlow Continuous Integration Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
        branches: [main]

jobs:
    TensorFlow-Tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            # Runs a set of commands using the runners shell
            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt install -y python3-pip
                  pip3 install tensorflow tensorflow-datasets
                  pip3 install -r requirements.txt --upgrade

            - name: Test runs
              run: |
                  ./run --config=configs/MNIST/fedavg_lenet5_tensorflow.yml
